# Generated by Django 2.2.3 on 2019-07-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puppies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puppies',
            name='breed',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='puppies',
            name='color',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='puppies',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
